# Generated by Django 5.1.3 on 2024-12-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_dt_habit_tm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("minutely", "ежеминутно"),
                    ("hourly", "ежечасно"),
                    ("daily", "ежедневно"),
                    ("weekly", "еженедельно"),
                ],
                default="daily",
                max_length=20,
                verbose_name="периодичность",
            ),
        ),
    ]
